-- Add Stage 3 tasks to the template
UPDATE transaction_stage_templates
SET tasks = '[
  {"title": "Create WhatsApp group & introduce all team members", "section": "GETTING STARTED", "description": ""},
  {"title": "Request Title & Instruments from Admin", "section": "GETTING STARTED", "description": ""},
  {"title": "Create Listing Folder in Google Drive", "section": "GETTING STARTED", "description": ""},
  {"title": "Create CMA and ensure it''s been sent to vendors/added to drive", "section": "GETTING STARTED", "description": ""},
  {"title": "Add Agency Agreement, Title and any other relevant docs to Google Drive", "section": "GETTING STARTED", "description": ""},
  {"title": "Add CMA to Google Drive", "section": "GETTING STARTED", "description": ""},
  {"title": "Complete AML", "section": "GETTING STARTED", "description": ""},
  {"title": "Add all known dates: listing expires, photoshoot, listing live, auction", "section": "GETTING STARTED", "description": ""},
  {"title": "Add all vendors'' details to NurtureCloud", "section": "GETTING STARTED", "description": ""},
  {"title": "Add Listing to Mark&Co Master Sheet", "section": "GETTING STARTED", "description": ""},
  {"title": "Send Formal Drive Email to vendors, including REAA books, CMA & Agency Agreement", "section": "GETTING STARTED", "description": ""},
  {"title": "Fill out Listing Checklist for Agent & return to Admin", "section": "GETTING STARTED", "description": ""},
  {"title": "Add Listing Live date to Google Calendar", "section": "GETTING STARTED", "description": ""},
  {"title": "Send vendors information on ordering their LIM via WhatsApp and email", "section": "GETTING STARTED", "description": ""},
  {"title": "Send information on Building Inspections to vendors", "section": "GETTING STARTED", "description": ""},
  {"title": "Send Campaign Calendar to vendors", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Send Marketing Proposal to vendors", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Create Final Campaign Calendar", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Book Auction with Craig Darroch", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Confirm photoshoot times with vendors", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Book Photography", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Confirm that Building Inspection is booked", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Confirm Marketing Package with vendors and send to ListNow", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Add photoshoot date to Google Calendar", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Setup Listing Folder in Vault (and now NurtureCloud)", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Add Auction date to Google Calendar", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Check to see if passing over stamp has been added to LIM & Title", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Add LIM to Google Drive", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Add Title to Google Drive", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Request Auction Agreement and the Sale & Purchase Agreement from Admin", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Add the Auction Contract and S&P to Google Drive Buyers folder", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Arrange Keys", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Invoice Annie for Mark&Co Services", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Write the video script/overview", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Create the Matterport Tour", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Carry out drone photo shoot", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Send links to property photography to vendors via WhatsApp", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Photos downloaded, ordered & put into Google Drive", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Bulk-SMS the Buyer SmartCall list", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Write the draft copy of the property advert", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Write the final version of the property advert & send to vendor for approval", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Create Canned Response in VaultRE", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Create Open Homes on NurtureCloud", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Create the Letter to Street in Canva", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Add property video to YouTube, Vault & Social Media", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Create Just Listed social media post (upload full video to Facebook)", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Create the Floorplan using CAPTUR3D", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Add Matterport link to MasterSheet", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Add Matterport tour to Linktree", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Add Matterport link to Boards", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Send Matterport tour via WhatsApp to vendors", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Create Social Media campaign via Austar", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Create Zapier for social media leads", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Design Open Home Brochure", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Design Property Signboard", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Create Just Listed flyer via Sharron Meek", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Create Building Report summary using ChatGPT", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Create LIM Report summary using ChatGPT", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Create Title Summary using ChatGPT", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Create Disclosure Document & get it signed by vendors", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Create new tab in Buyer Tracker Google Sheet", "section": "PROPERTY MARKETING", "description": ""},
  {"title": "Add entire SmartCall buyer list to property enquiries", "section": "PROPERTY MARKETING", "description": ""}
]'::jsonb
WHERE id = '53eea6d3-be66-401b-8f73-d2f2c772388e';