-- Add Stage 2 tasks to the template
UPDATE transaction_stage_templates
SET tasks = '[
  {"title": "Create WhatsApp group & introduce all team members", "section": "GETTING STARTED", "description": ""},
  {"title": "Request Title & Instruments from Admin", "section": "GETTING STARTED", "description": ""},
  {"title": "Create Listing Folder in Google Drive", "section": "GETTING STARTED", "description": ""},
  {"title": "Create CMA and ensure it''s been sent to vendors/added to drive", "section": "GETTING STARTED", "description": ""},
  {"title": "Add Agency Agreement, Title and any other relevant docs to Google Drive", "section": "GETTING STARTED", "description": ""},
  {"title": "Add CMA to Google Drive", "section": "GETTING STARTED", "description": ""},
  {"title": "Complete AML", "section": "GETTING STARTED", "description": ""},
  {"title": "Add all known dates: listing expires, photoshoot, listing live, auction", "section": "GETTING STARTED", "description": ""},
  {"title": "Add all vendors'' details to NurtureCloud", "section": "GETTING STARTED", "description": ""},
  {"title": "Add Listing to Mark&Co Master Sheet", "section": "GETTING STARTED", "description": ""},
  {"title": "Send Formal Drive Email to vendors, including REAA books, CMA & Agency Agreement", "section": "GETTING STARTED", "description": ""},
  {"title": "Fill out Listing Checklist for Agent & return to Admin", "section": "GETTING STARTED", "description": ""},
  {"title": "Add Listing Live date to Google Calendar", "section": "GETTING STARTED", "description": ""},
  {"title": "Send vendors information on ordering their LIM via WhatsApp and email", "section": "GETTING STARTED", "description": ""},
  {"title": "Send information on Building Inspections to vendors", "section": "GETTING STARTED", "description": ""},
  {"title": "Send Campaign Calendar to vendors", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Send Marketing Proposal to vendors", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Create Final Campaign Calendar", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Book Auction with Craig Darroch", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Confirm photoshoot times with vendors", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Book Photography", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Confirm that Building Inspection is booked", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Confirm Marketing Package with vendors and send to ListNow", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Add photoshoot date to Google Calendar", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Setup Listing Folder in Vault (and now NurtureCloud)", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Add Auction date to Google Calendar", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Check to see if passing over stamp has been added to LIM & Title", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Add LIM to Google Drive", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Add Title to Google Drive", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Request Auction Agreement and the Sale & Purchase Agreement from Admin", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Add the Auction Contract and S&P to Google Drive Buyers folder", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Arrange Keys", "section": "CONFIRMING DETAILS", "description": ""},
  {"title": "Invoice Annie for Mark&Co Services", "section": "CONFIRMING DETAILS", "description": ""}
]'::jsonb
WHERE id = '53eea6d3-be66-401b-8f73-d2f2c772388e';