
-- Add tasks to Unconditional template
UPDATE transaction_stage_templates 
SET tasks = tasks || '[
  {"title": "Setup Buyers WhatsApp group (unless already created)", "section": "SETUP", "priority": "high", "due_offset_days": 0},
  {"title": "Congratulate the buyers on going unconditional", "section": "COMMUNICATIONS", "priority": "high", "due_offset_days": 0},
  {"title": "Send Congratulations - Unconditional email to buyers with deposit details", "section": "COMMUNICATIONS", "priority": "high", "due_offset_days": 0},
  {"title": "Send Congratulations - Unconditional email to vendors", "section": "COMMUNICATIONS", "priority": "high", "due_offset_days": 0},
  {"title": "Create Transaction Report and add/send to all parties/areas", "section": "ADMIN", "priority": "high", "due_offset_days": 0},
  {"title": "Sold - Put Sold Sticker on property & take photo", "section": "SOLD TASKS", "priority": "medium", "due_offset_days": 0},
  {"title": "Sold - SMS blast to all registered buyers", "section": "SOLD TASKS", "priority": "medium", "due_offset_days": 0},
  {"title": "Sold - Send Just Sold Email to potential sellers in suburb", "section": "SOLD TASKS", "priority": "medium", "due_offset_days": 0},
  {"title": "Sold - Call Past Appraisal list in street/surrounding streets & notify of sale", "section": "SOLD TASKS", "priority": "medium", "due_offset_days": 0},
  {"title": "Update price on OneHub (TradeMe) and RateMyAgent", "section": "ADMIN", "priority": "medium", "due_offset_days": 0},
  {"title": "CCM Gift Box delivered", "section": "GIFTS & FOLLOW-UP", "priority": "medium", "due_offset_days": 0},
  {"title": "Send Feedback Request to Buyer via RateMyAgent", "section": "FEEDBACK", "priority": "medium", "due_offset_days": 0},
  {"title": "Send Feedback Request to Vendor via RateMyAgent", "section": "FEEDBACK", "priority": "medium", "due_offset_days": 0},
  {"title": "Order photo-book for buyers & vendors from Sharron Meek", "section": "GIFTS & FOLLOW-UP", "priority": "low", "due_offset_days": 0},
  {"title": "Update Mark & Co Mastersheet with listing/sale details", "section": "ADMIN", "priority": "medium", "due_offset_days": 0},
  {"title": "Add Settlement Date to Google Calendar", "section": "SETTLEMENT PREP", "priority": "high", "due_offset_days": 0},
  {"title": "Post Packing Checklist document to Vendor", "section": "SETTLEMENT PREP", "priority": "medium", "due_offset_days": 0},
  {"title": "Confirm deposit paid - check with Annie", "section": "ADMIN", "priority": "high", "due_offset_days": 0},
  {"title": "Create Just Sold campaign for social media", "section": "MARKETING", "priority": "medium", "due_offset_days": 0},
  {"title": "Order 50 Just-Sold DL flyers from Sharron Meek", "section": "MARKETING", "priority": "medium", "due_offset_days": 0},
  {"title": "Deliver 50 Just-Sold letters to street (door knock, target 10x10x20)", "section": "MARKETING", "priority": "medium", "due_offset_days": 0},
  {"title": "Reply to Google My Business review", "section": "FEEDBACK", "priority": "medium", "due_offset_days": 0},
  {"title": "Add feedback + selfie to Drive & Mastersheet", "section": "FEEDBACK", "priority": "low", "due_offset_days": 0},
  {"title": "Arrange Tracey to deliver DL flyers (avoid actual street?)", "section": "MARKETING", "priority": "low", "due_offset_days": 0},
  {"title": "WhatsApp: Did you receive Packing Checklist?", "section": "SETTLEMENT PREP", "priority": "medium", "due_offset_days": 0},
  {"title": "Send vendor pre-settlement inspection template email", "section": "PRE-SETTLEMENT", "priority": "high", "due_offset_days": 0},
  {"title": "Send buyer pre-settlement inspection template email", "section": "PRE-SETTLEMENT", "priority": "high", "due_offset_days": 0},
  {"title": "Add Pre-Settlement Inspection to Google Calendar", "section": "PRE-SETTLEMENT", "priority": "high", "due_offset_days": 0},
  {"title": "Send buyer pre-settlement inspection follow-up template email", "section": "PRE-SETTLEMENT", "priority": "medium", "due_offset_days": 0},
  {"title": "WhatsApp follow-up: Did you receive Packing Checklist?", "section": "SETTLEMENT PREP", "priority": "medium", "due_offset_days": 0},
  {"title": "Send follow-up request for feedback (if not received)", "section": "FEEDBACK", "priority": "low", "due_offset_days": 0},
  {"title": "Send Settlement Day template email to buyers", "section": "SETTLEMENT DAY", "priority": "high", "due_offset_days": 0},
  {"title": "Send Settlement Day template email to vendors", "section": "SETTLEMENT DAY", "priority": "high", "due_offset_days": 0},
  {"title": "Confirm how Settlement Day will work with vendors & buyers", "section": "SETTLEMENT DAY", "priority": "high", "due_offset_days": 0},
  {"title": "Add schedule, time and details to Google Calendar", "section": "SETTLEMENT DAY", "priority": "high", "due_offset_days": 0},
  {"title": "WhatsApp: Confirm full key set delivered to office for settlement", "section": "SETTLEMENT DAY", "priority": "high", "due_offset_days": 0},
  {"title": "Put yellow bow on door", "section": "SETTLEMENT DAY", "priority": "medium", "due_offset_days": 0},
  {"title": "WhatsApp: Confirm forwarding address etc. & update NurtureCloud", "section": "POST-SETTLEMENT", "priority": "medium", "due_offset_days": 0},
  {"title": "Send/deliver photobook to vendors", "section": "POST-SETTLEMENT", "priority": "low", "due_offset_days": 0},
  {"title": "Archive Matterport tour", "section": "CLEANUP", "priority": "low", "due_offset_days": 0},
  {"title": "Remove Board links to Matterport & VaultRE", "section": "CLEANUP", "priority": "low", "due_offset_days": 0},
  {"title": "Update Linktree & remove listing link", "section": "CLEANUP", "priority": "low", "due_offset_days": 0},
  {"title": "Add Purchasers & Vendors to VIP/Settlement Anniversaries Google Sheet", "section": "POST-SETTLEMENT", "priority": "medium", "due_offset_days": 0},
  {"title": "Add vendors & purchasers to Settlement Anniversary list", "section": "POST-SETTLEMENT", "priority": "medium", "due_offset_days": 0},
  {"title": "Send SMS to local homeowners via NC announcing sale", "section": "MARKETING", "priority": "medium", "due_offset_days": 0}
]'::jsonb,
updated_at = now()
WHERE id = '31a142b8-d00e-4f9b-a3cc-9578805f85ab';
