-- Phase 2: Seed 8 essential system templates for real estate

INSERT INTO note_templates (title, description, content_rich, category, is_system, created_by)
VALUES
-- 1. Client Meeting Notes
(
  'Client Meeting Notes',
  'Comprehensive template for client meetings and discovery calls',
  '{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Client Meeting Notes"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Client Details"}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Name:"}, {"type":"text","text":" "}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Contact:"}, {"type":"text","text":" "}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Type:"}, {"type":"text","text":" Buyer / Seller / Investor"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Meeting Purpose"}]},{"type":"paragraph","content":[{"type":"text","text":"What prompted this meeting:"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Discussion Points"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Key topic 1"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Key topic 2"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Key topic 3"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Action Items"}]},{"type":"taskList","content":[{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Follow up task 1"}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Follow up task 2"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Next Steps"}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Follow-up Date:"}, {"type":"text","text":" "}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Next Contact:"}, {"type":"text","text":" "}]}]}',
  'meetings',
  true,
  NULL
),

-- 2. Property Inspection Checklist
(
  'Property Inspection Checklist',
  'Detailed checklist for property inspections and appraisals',
  '{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Property Inspection Checklist"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Property Details"}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Address:"}, {"type":"text","text":" "}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Inspection Date:"}, {"type":"text","text":" "}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Property Type:"}, {"type":"text","text":" House / Apartment / Townhouse"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Exterior Condition"}]},{"type":"taskList","content":[{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Roof condition"}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Gutters and drainage"}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Walls and paint"}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Driveway and pathways"}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Garden and landscaping"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Interior Rooms"}]},{"type":"taskList","content":[{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Kitchen condition"}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Bathrooms"}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Living areas"}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Bedrooms"}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Flooring condition"}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Windows and doors"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Issues Found"}]},{"type":"paragraph","content":[{"type":"text","text":"List any issues or concerns:"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Overall Assessment"}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Estimated Value:"}, {"type":"text","text":" $"}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Recommendation:"}, {"type":"text","text":" "}]}]}',
  'listings',
  true,
  NULL
),

-- 3. Open Home Preparation
(
  'Open Home Preparation',
  'Checklist and plan for organizing successful open homes',
  '{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Open Home Preparation"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Event Details"}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Property:"}, {"type":"text","text":" "}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Date & Time:"}, {"type":"text","text":" "}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Duration:"}, {"type":"text","text":" "}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Marketing Materials"}]},{"type":"taskList","content":[{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Brochures printed"}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Sign-in sheet prepared"}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Business cards ready"}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Property information sheets"}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"For Sale signage"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Venue Setup"}]},{"type":"taskList","content":[{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Property cleaned and staged"}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Lights on, curtains open"}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Temperature comfortable"}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Music playing (optional)"}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Refreshments prepared"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"After Open Home"}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Total Visitors:"}, {"type":"text","text":" "}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Serious Inquiries:"}, {"type":"text","text":" "}]},{"type":"paragraph","content":[{"type":"text","text":"Feedback notes:"}]}]}',
  'events',
  true,
  NULL
),

-- 4. Market Analysis
(
  'Market Analysis',
  'Template for researching and analyzing property markets',
  '{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Market Analysis"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Property Details"}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Address:"}, {"type":"text","text":" "}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Property Type:"}, {"type":"text","text":" "}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Bedrooms/Bathrooms:"}, {"type":"text","text":" "}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Comparable Sales"}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Comp 1:"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Address: "}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Sale Price: $"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Sale Date: "}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Features: "}]}]}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Comp 2:"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Address: "}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Sale Price: $"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Sale Date: "}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Market Trends"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Current market conditions"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Days on market average"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Price trends (up/down/stable)"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Buyer demand level"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Pricing Strategy"}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Recommended List Price:"}, {"type":"text","text":" $"}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Expected Sale Range:"}, {"type":"text","text":" $     - $"}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Reasoning:"}, {"type":"text","text":" "}]}]}',
  'listings',
  true,
  NULL
),

-- 5. Vendor Meeting Notes
(
  'Vendor Meeting Notes',
  'Template for meetings with property vendors and sellers',
  '{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Vendor Meeting Notes"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Vendor Information"}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Name:"}, {"type":"text","text":" "}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Property:"}, {"type":"text","text":" "}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Meeting Date:"}, {"type":"text","text":" "}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Discussion Points"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Reason for selling"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Timeline expectations"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Price expectations"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Property condition & improvements"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Agreement Terms"}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Commission:"}, {"type":"text","text":" "}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Contract Period:"}, {"type":"text","text":" "}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Marketing Plan:"}, {"type":"text","text":" "}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Action Items"}]},{"type":"taskList","content":[{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Prepare listing agreement"}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Schedule property photos"}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Arrange appraisal"}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Create marketing materials"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Next Steps"}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Next Meeting:"}, {"type":"text","text":" "}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Expected Listing Date:"}, {"type":"text","text":" "}]}]}',
  'vendors',
  true,
  NULL
),

-- 6. Weekly Team Meeting
(
  'Weekly Team Meeting',
  'Structured agenda for team meetings and pipeline reviews',
  '{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Weekly Team Meeting"}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Date:"}, {"type":"text","text":" "}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Attendees:"}, {"type":"text","text":" "}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Week in Review"}]},{"type":"paragraph","content":[{"type":"text","text":"Key achievements from last week:"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Achievement 1"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Achievement 2"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Wins & Challenges"}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Wins:"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Win 1"}]}]}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Challenges:"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Challenge 1"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Pipeline Update"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"New listings: "}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Active properties: "}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Under contract: "}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Settlements this week: "}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"This Week''s Focus"}]},{"type":"taskList","content":[{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Priority 1"}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Priority 2"}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Priority 3"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Action Items"}]},{"type":"taskList","content":[{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Action 1 - Owner: "}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Action 2 - Owner: "}]}]}]}]}',
  'meetings',
  true,
  NULL
),

-- 7. Lead Follow-up
(
  'Lead Follow-up',
  'Quick template for tracking lead interactions and next steps',
  '{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Lead Follow-up"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Lead Information"}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Name:"}, {"type":"text","text":" "}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Phone:"}, {"type":"text","text":" "}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Email:"}, {"type":"text","text":" "}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Source:"}, {"type":"text","text":" Website / Open Home / Referral / Other"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Initial Interest"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Property type: "}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Price range: $"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Timeline: "}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Motivation: "}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Conversation Notes"}]},{"type":"paragraph","content":[{"type":"text","text":"Key points from discussion:"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Follow-up Actions"}]},{"type":"taskList","content":[{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Send property listings"}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Schedule property viewing"}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Arrange finance pre-approval"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Next Contact"}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Next Contact Date:"}, {"type":"text","text":" "}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Preferred Method:"}, {"type":"text","text":" Phone / Email / SMS"}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Reminder:"}, {"type":"text","text":" "}]}]}',
  'personal',
  true,
  NULL
),

-- 8. Simple Notes
(
  'Simple Notes',
  'Blank template with basic formatting for quick notes',
  '{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Notes"}]},{"type":"paragraph","content":[{"type":"text","text":"Start typing..."}]},{"type":"paragraph"},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Key Points"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Point 1"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Point 2"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Action Items"}]},{"type":"taskList","content":[{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Task 1"}]}]},{"type":"taskItem","attrs":{"checked":false},"content":[{"type":"paragraph","content":[{"type":"text","text":"Task 2"}]}]}]}]}',
  'general',
  true,
  NULL
);