// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Cookie configuration for enhanced security
    // SameSite=Lax provides CSRF protection while allowing normal navigation
    storageKey: 'supabase.auth.token',
    flowType: 'pkce',
  },
  global: {
    // Add X-Requested-With header to all requests for CSRF-like protection
    headers: {
      'X-Requested-With': 'XMLHttpRequest',
    },
  },
});